# Generated by Django 6.0.3 on 2026-04-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
