# Generated by Django 6.0.3 on 2026-04-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_likes_post_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
